import { Download, FileText } from "lucide-react";
import { exportCsv, exportPdf, type ReportColumn } from "../../../../services/reportService";
import type { Task } from "../../../tasks";
import type { ProjectCommandData } from "./types";

const COLUMNS: ReportColumn<Task>[] = [
  { key: "title", header: "Task", value: (task) => task.title },
  { key: "status", header: "Status", value: (task) => task.status.replace(/_/g, " ") },
  { key: "lead", header: "Task Lead", value: (task) => task.assigneeName || "Unassigned" },
  { key: "progress", header: "Progress", value: (task) => `${task.status === "completed" ? 100 : task.percentComplete || 0}%` },
  { key: "deadline", header: "Deadline", value: (task) => task.deadline || task.dueDate || "Unscheduled" },
  { key: "subtasks", header: "Subtasks", value: (task) => task.subtaskCount || 0 },
];

export function ProjectReportsTab({ data, canExport }: { data: ProjectCommandData; canExport: boolean }) {
  const meta = { title: `${data.project.title} Project Report`, subtitle: "Activities, work progress, people, evidence and review health", filters: { project: data.project.title, status: data.project.status }, totals: { progress: `${data.metrics.progress}%`, tasks: data.metrics.taskTotal, milestones: data.milestones.length, evidence: data.facts.evidence.length, review_queue: data.metrics.awaitingReview } };
  return <div className="space-y-4"><section className="rounded-2xl border border-neutral-200 bg-gradient-to-br from-neutral-950 to-neutral-800 p-5 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-[9px] font-semibold uppercase tracking-[0.14em] text-neutral-400">Project report package</div><h3 className="mt-1 text-[17px] font-semibold">{data.project.title}</h3><p className="mt-1 max-w-xl text-[10.5px] leading-relaxed text-neutral-300">Exports use the exact project rows already visible to this user. RLS scope is never widened for reporting.</p></div>{canExport ? <div className="flex gap-2"><button type="button" onClick={() => exportCsv(data.tasks, COLUMNS, meta)} className="inline-flex items-center gap-1.5 rounded-xl bg-white px-3 py-2 text-[10.5px] font-semibold text-neutral-900"><Download size={12} /> CSV</button><button type="button" onClick={() => exportPdf(data.tasks, COLUMNS, meta)} className="inline-flex items-center gap-1.5 rounded-xl border border-white/20 bg-white/10 px-3 py-2 text-[10.5px] font-semibold text-white"><FileText size={12} /> PDF</button></div> : null}</div></section><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{[["Schedule and progress", `${data.metrics.taskCompleted}/${data.metrics.taskTotal} tasks approved`, `${data.metrics.overdue} overdue · ${data.metrics.milestoneOpen} open activities`], ["People contribution", `${data.metrics.activeLeadIds.length} active Task Leads`, `${data.members.length} project members`], ["Evidence and review", `${data.facts.evidence.length} evidence files`, `${data.metrics.awaitingReview} waiting · ${data.metrics.changesRequested} revisions`], ["Blockers and risk", `${data.metrics.blocked} active blockers`, `${data.attention.length} total attention items`], ["Subtask execution", `${data.facts.subtasks.filter((item) => item.status === "completed").length}/${data.facts.subtasks.length} leader approved`, `${data.facts.progress.filter((item) => item.kind === "subtask").length} contributor updates`], ["Review history", `${data.facts.submissions.filter((item) => item.status === "approved").length} approvals`, `${data.facts.submissions.length} total attempts`]].map(([title, value, hint]) => <div key={title} className="rounded-2xl border border-neutral-200 bg-white p-4"><div className="text-[9px] font-semibold uppercase tracking-[0.12em] text-neutral-400">{title}</div><div className="mt-2 text-[14px] font-semibold text-neutral-900">{value}</div><div className="mt-1 text-[9.5px] text-neutral-400">{hint}</div></div>)}</div></div>;
}
