import { AlertTriangle, Building2, Calendar, ChevronRight, Clock3, UsersRound } from "lucide-react";
import type { Project } from "../../../services/projectService";
import type { Task } from "../../tasks";
import type { Organization, UserProfile } from "../../../types";
import { ProgressBar, formatDate } from "../../../components/workflow/primitives";
import { PriorityPill, ProjectStatusBadge } from "../../../components/workflow/StatusBadges";
import { buildProjectPortfolioSummary } from "../selectors/projectCommandSelectors";

const HEALTH = { on_track: "bg-emerald-50 text-emerald-700", due_soon: "bg-amber-50 text-amber-700", overdue: "bg-red-50 text-red-700", at_risk: "bg-orange-50 text-orange-700", completed: "bg-blue-50 text-blue-700" } as const;

export function ProjectCard({ project, tasks, orgs, profiles, onOpen, view = "grid" }: { project: Project; tasks: Task[]; orgs: Organization[]; profiles: UserProfile[]; onOpen: () => void; view?: "grid" | "list" }) {
  const summary = buildProjectPortfolioSummary(project, tasks); const orgName = orgs.find((org) => org.id === project.orgId)?.name; const owner = profiles.find((profile) => profile.id === project.ownerId); const leads = summary.leadIds.map((id) => profiles.find((profile) => profile.id === id)?.full_name).filter(Boolean); const healthClass = summary.isEmpty ? "bg-neutral-100 text-neutral-600" : HEALTH[summary.health]; const healthLabel = summary.isEmpty ? "empty project" : summary.health.replace(/_/g, " ");
  if (view === "list") return <button type="button" onClick={onOpen} className="grid w-full items-center gap-3 rounded-xl border border-neutral-200 bg-white px-4 py-3 text-left transition hover:border-neutral-300 hover:shadow-sm lg:grid-cols-[minmax(220px,1.5fr)_110px_170px_140px_120px_auto]"><div className="min-w-0"><div className="flex items-center gap-2"><ProjectStatusBadge status={project.status} size="sm" /><span className="truncate text-[11.5px] font-semibold text-neutral-900">{project.title}</span></div><div className="mt-1 truncate text-[9.5px] text-neutral-400">{orgName || "No department"} · {owner?.full_name || "No owner"}</div></div><span className={`w-fit rounded-full px-2 py-1 text-[8.5px] font-semibold capitalize ${healthClass}`}>{healthLabel}</span><div><div className="flex justify-between text-[9px] text-neutral-400"><span>{summary.completed}/{summary.total} tasks</span><span>{summary.progress}%</span></div><div className="mt-1"><ProgressBar value={summary.progress} tone={summary.progress === 100 ? "good" : "neutral"} /></div></div><span className="truncate text-[9.5px] text-neutral-500">{leads.join(", ") || "No active lead"}</span><span className="text-[9.5px] text-neutral-400">{formatDate(summary.nextDeadline)}</span><ChevronRight size={14} className="text-neutral-300" /></button>;
  return <button type="button" onClick={onOpen} className="group rounded-2xl border border-neutral-200 bg-white p-4 text-left transition-all hover:-translate-y-0.5 hover:border-neutral-300 hover:shadow-md"><div className="flex items-start justify-between gap-2"><div className="flex flex-wrap items-center gap-1.5"><ProjectStatusBadge status={project.status} size="sm" /><span className={`rounded-full px-2 py-0.5 text-[8px] font-semibold capitalize ${healthClass}`}>{healthLabel}</span></div><PriorityPill priority={project.priority} /></div><h3 className="mt-3 line-clamp-2 text-[13.5px] font-semibold leading-snug text-neutral-900">{project.title}</h3><p className="mt-1 line-clamp-2 min-h-[30px] text-[9.5px] leading-relaxed text-neutral-400">{project.description || "No description"}</p><div className="mt-3 flex items-center gap-1 text-[9.5px] text-neutral-400"><Building2 size={10} /> {orgName || "No department"}</div><div className="mt-3"><div className="mb-1 flex justify-between text-[9.5px] text-neutral-500"><span>{summary.completed}/{summary.total} tasks</span><span className="font-semibold text-neutral-700">{summary.progress}%</span></div><ProgressBar value={summary.progress} tone={summary.progress === 100 ? "good" : "neutral"} /></div><div className="mt-3 grid grid-cols-3 gap-1.5"><Signal icon={<AlertTriangle size={10} />} value={summary.overdue} label="overdue" bad={summary.overdue > 0} /><Signal icon={<Clock3 size={10} />} value={summary.awaitingReview} label="reviews" bad={summary.awaitingReview > 0} /><Signal icon={<UsersRound size={10} />} value={summary.leadIds.length} label="leads" /></div><div className="mt-3 flex items-center justify-between border-t border-neutral-100 pt-3 text-[9.5px] text-neutral-400"><span className="inline-flex items-center gap-1"><Calendar size={10} /> {formatDate(summary.nextDeadline)}</span><span className="truncate">{owner?.full_name || "No owner"}</span></div></button>;
}
function Signal({ icon, value, label, bad }: { icon: React.ReactNode; value: number; label: string; bad?: boolean }) { return <span className={`inline-flex items-center justify-center gap-1 rounded-lg px-1.5 py-1 text-[8.5px] ${bad ? "bg-red-50 text-red-700" : "bg-neutral-50 text-neutral-500"}`}>{icon}{value} {label}</span>; }
